In [1]:
#load libraries
require(tidyr)
require(dplyr)

Loading required package: tidyr

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [43]:
#load Colony_Data.csv
colony=read.csv("~/Documents/SCTLD/SCTLD_samples/Sample_Data/CBC_ColonyData.csv")

In [44]:
head(colony)

  X Date_InitialTag Transect TransectNum OldTagNum NewTagNum Species Meter
1 1 6/21/19         CBC30N   1           349       1         SSID    1.5
2 2 6/21/19         CBC30N   1           334       2         PAST    1.4
3 3 6/21/19         CBC30N   1           346       3         SSID    6.3
4 4 10/15/19        CBC30N   1           407       4         PSTR    6.5
5 5 6/24/19         CBC30N   1           394       5         SSID    4.3
6 6 10/15/19        CBC30N   1           413       6         PSTR    8.3
  Meters_90 Direction ⋯ X082024_Percentage
1 0.50      right     ⋯
2 0.10      left      ⋯
3 0.80      right     ⋯
4 0.50      right     ⋯
5 1.20      left      ⋯
6 1.75      left      ⋯
  Notes_082024
1
2 sample lower colony (original colony); inc old mort; too small for immune
3 some discoloration
4
5
6
  X122024_Condition X122024_Percentage Notes_122024  X062025_Condition
1 Not_visited                          Diseased      Diseased
2                                                    Healthy
3 DC                10%                30% mortality Diseased
4 Dead                                 Dead          Dead
5 DC                10%                80% mortality Diseased
6 Dead                                               Dead
  X062025_Percentage Notes_062025 immune_y.n checked_colonies
1                                 n          x
2                                 y          x
3                                 y          x
4                                 n          x
5                                 n          x
6                                 n          x

In [45]:
#isolate non-immune samples from colony data and focus on samples that got disease
colony_nonimmune=colony[colony$immune_y.n=="n",]
colony_nonimmune <- colony_nonimmune[colony_nonimmune$Date_DocumentedDisease!= "Healthy",]
colony_nonimmune=as.vector(paste0(colony_nonimmune$TransectNum,"_", colony_nonimmune$NewTagNum))

In [46]:
#load metagenomics data
metagenomics=read.csv("~/Documents/SCTLD/SCTLD_samples/Sample_Data/Metagenomics_Tracker_Belize.csv")

In [47]:
sample=read.csv("~/Documents/SCTLD/SCTLD_samples/Sample_Data/CBC_samples.csv")

# sample_dna add colony column to sample data
sample$colony= colony= c(paste0(sample$TransectNum, "_", sample$NewTagNum))

#clean sample data of leading spaces
sample$Month_year <- trimws(sample$Month_year)
sample$Health_status <- trimws(sample$Health_status)

# only utilize correct species, and EtOH + RNALater samples and exclue 062025 samples
sample_DNA <- sample[(sample$Sample_type == "Core_EtOH" | sample$Sample_type == "Core_RNAlater") & 
    sample$Month_year != "62025",]

head(sample_DNA)
#double check that all 062025 samples have been removed
unique(sample_clean$Month_year)

  Month_year Country Location CollectionDate Transect TransectNum OldTagNum
2 92023      BEL     CBC      9/27/23        CBC30N   1
3 92023      BEL     CBC      9/25/23        CBC30N   1
4 92023      BEL     CBC      9/25/23        CBC30N   1
5 92023      BEL     CBC      9/25/23        CBC30N   1
6 92023      BEL     CBC      9/25/23        CBC30N   1
7 92023      BEL     CBC      9/27/23        CBC30N   1
  NewTagNum Species Time_sampled ⋯ Sample_type   SampleNum Health_status
2 1         SSID                 ⋯ Core_RNAlater 185       Diseased_Margin
3 2         PAST                 ⋯ Core_RNAlater 171       Bleached_Tissue
4 3         SSID                 ⋯ Core_RNAlater 173       Healthy
5 12        PSTR                 ⋯ Core_RNAlater 177       Healthy
6 13        PAST                 ⋯ Core_RNAlater 175       Healthy
7 5         SSID                 ⋯ Core_RNAlater 188       Diseased_Tissue
  Sampling_notes               Tubelabel_species
2 only margin sample available 092023_BEL_CBC_T1_185_SSID
3 CLP 90%                      092023_BEL_CBC_T1_171_PAST
4 CLP 80%; DC 20%              092023_BEL_CBC_T1_173_SSID
5 No CL                        092023_BEL_CBC_T1_177_PSTR
6 No CL                        092023_BEL_CBC_T1_175_PAST
7                              092023_BEL_CBC_T1_188_SSID
  Sample_physical_location Extraction_physical_location Date_sequenced
2 UML_NARWHAL_R1_B10
3 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
4 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
5 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
6 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
7 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B11
  Notes                  colony
2                        1_1
3                        1_2
4                        1_3
5                        1_12
6 R2_B15 EXTRACTED TWICE 1_13
7                        1_5

NULL

In [51]:
#extract rows where points is greater than 90 and assists is greater than 33
sample_clean <- sample_DNA[sample_DNA$Species == "MCAV"|sample_DNA$Species == "PSTR"|sample_DNA$Species == "SSID"|sample_DNA$Species == "PAST"|sample_DNA$Species == "OFAV"|sample_DNA$Species == "OANN", ]

#view sample_clean, this is a new table modeled after sample data sheet and utilizing the colony tag num as a column
head(sample_clean)

  Month_year Country Location CollectionDate Transect TransectNum OldTagNum
2 92023      BEL     CBC      9/27/23        CBC30N   1
3 92023      BEL     CBC      9/25/23        CBC30N   1
4 92023      BEL     CBC      9/25/23        CBC30N   1
5 92023      BEL     CBC      9/25/23        CBC30N   1
6 92023      BEL     CBC      9/25/23        CBC30N   1
7 92023      BEL     CBC      9/27/23        CBC30N   1
  NewTagNum Species Time_sampled ⋯ Sample_type   SampleNum Health_status
2 1         SSID                 ⋯ Core_RNAlater 185       Diseased_Margin
3 2         PAST                 ⋯ Core_RNAlater 171       Bleached_Tissue
4 3         SSID                 ⋯ Core_RNAlater 173       Healthy
5 12        PSTR                 ⋯ Core_RNAlater 177       Healthy
6 13        PAST                 ⋯ Core_RNAlater 175       Healthy
7 5         SSID                 ⋯ Core_RNAlater 188       Diseased_Tissue
  Sampling_notes               Tubelabel_species
2 only margin sample available 092023_BEL_CBC_T1_185_SSID
3 CLP 90%                      092023_BEL_CBC_T1_171_PAST
4 CLP 80%; DC 20%              092023_BEL_CBC_T1_173_SSID
5 No CL                        092023_BEL_CBC_T1_177_PSTR
6 No CL                        092023_BEL_CBC_T1_175_PAST
7                              092023_BEL_CBC_T1_188_SSID
  Sample_physical_location Extraction_physical_location Date_sequenced
2 UML_NARWHAL_R1_B10
3 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
4 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
5 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
6 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B12
7 UML_NARWHAL_R1_B10       UML_NARWHAL_R2_B11
  Notes                  colony
2                        1_1
3                        1_2
4                        1_3
5                        1_12
6 R2_B15 EXTRACTED TWICE 1_13
7                        1_5

In [52]:
nrow(sample_DNA)
nrow(sample_clean)

[1] 868

[1] 821

In [53]:
#changing X column to Tubelabel_species
names(metagenomics)[names(metagenomics) == 'X'] <- 'Tubelabel_species'
colnames(metagenomics)

 [1] "Tubelabel_species"
 [2] "Health_Status"
 [3] "Starting_Weight"
 [4] "Date_Extracted"
 [5] "Raw_ng_ul"
 [6] "Date_Enriched"
 [7] "Microbe_ng_ul"
 [8] "Microbe_Location"
 [9] "Microbe_clean_date.n"
[10] "Host_ng_ul"
[11] "Host_Location"
[12] "Host_clean_y.n"
[13] "Date_Libprep"
[14] "Status"
[15] "Notes"
[16] "Seq_date"
[17] "Host_Seq_date"
[18] "Microbe_seq_file"
[19] "Host_seq_file"
[20] "Seq_Location..in.Unity."
[21] "Sample_physical_location"
[22] "Extraction_physical_location"
[23] "Location_notes"
[24] "Sample_Code...datecollected_tagnumber_transect_samplenumber_species"

In [54]:
#the columns that I want to isolate from metagenomics tracker
metagenomics_PCR = metagenomics[c("Tubelabel_species", "Health_Status", "Date_Extracted", "Raw_ng_ul", "Extraction_physical_location", "Date_Enriched","Microbe_Location")]

In [55]:
head(metagenomics_PCR)

  Tubelabel_species          Health_Status   Date_Extracted Raw_ng_ul
1 052022_BEL_CBC_T2_45_PSTR  Diseased_Margin 10_10_2023     22.8
2 052022_BEL_CBC_T2_46_PSTR  Diseased_Tissue 10_10_2023     63.9
3 052022_BEL_CBC_T2_59_OFAV  Healthy         10_3_2023      73.7
4 042024_BEL_CBC_T1_925_PAST Healthy         8_19_2024      5.46
5 052022_BEL_CBC_T2_72_OFAV  Healthy         10_3_2023      47.6
6 052022_BEL_CBC_T2_71_OFAV  Healthy         10_3_2023      98.8
  Extraction_physical_location Date_Enriched Microbe_Location
1 UML_NARWHAL_R2_B3            10_17_2023    UML_NARWHAL_R2_B1
2 UML_NARWHAL_R2_B3            10_17_2023    UML_NARWHAL_R2_B1
3 UML_NARWHAL_R2_B3            10_16_2023    UML_NARWHAL_R2_B1
4 UML_NARWHAL_R2_B29           9_28_2024     UML_NARWHAL_R6_B30
5 UML_NARWHAL_R2_B3            10_11_23      UML_NARWHAL_R6_B1
6 UML_NARWHAL_R2_B3            10_16_2023    UML_NARWHAL_R6_B1

In [56]:
#info I am using to create ties between sample_dna and metagenomics_PCR
sample_clean=sample_clean[c("Tubelabel_species", "colony")]

In [57]:
#only including immune samples in sample_DNA
nonimmune_sample=sample_clean[sample_clean$colony %in% colony_nonimmune,]

In [58]:
head(nonimmune_sample)
nrow(nonimmune_sample)

   Tubelabel_species          colony
2  092023_BEL_CBC_T1_185_SSID 1_1
7  092023_BEL_CBC_T1_188_SSID 1_5
8  092023_BEL_CBC_T1_189_SSID 1_5
10 092023_BEL_CBC_T1_192_SSID 1_9
11 092023_BEL_CBC_T1_193_SSID 1_11
15 092023_BEL_CBC_T1_194_SSID 1_16

[1] 248

In [59]:
nrow(metagenomics_PCR)

#check to see why there is a discrepancy from immune_sample_DNA to_metagenomics_PCR
unmatched=anti_join(nonimmune_sample,metagenomics_PCR, by='Tubelabel_species')
nrow(unmatched)

[1] 557

[1] 134

In [60]:
# inner join 
nonimmune_PCR <- merge(x=metagenomics_PCR,y=nonimmune_sample, 
                by="Tubelabel_species")
head(nonimmune_PCR)

  Tubelabel_species           Health_Status   Date_Extracted Raw_ng_ul
1 042024_BEL_CBC_T1_1146_OANN Diseased_Tissue 9_9_2024       14.6
2 042024_BEL_CBC_T1_933_SSID  Diseased_Tissue 9_9_2024       25.4
3 042024_BEL_CBC_T1_938_SSID  Diseased_Tissue 9_9_2024       4.08
4 042024_BEL_CBC_T1_940_SSID  Diseased_Tissue 9_9_2024       63.2
5 042024_BEL_CBC_T2_1030_SSID Diseased_Tissue 9_9_2024       24.6
6 042024_BEL_CBC_T3_1011_SSID Diseased_Tissue 9_9_2024       7.42
  Extraction_physical_location Date_Enriched Microbe_Location colony
1 UML_NARWHAL_R2_B11                                          1_22
2 UML_NARWHAL_R2_B11                                          1_5
3 UML_NARWHAL_R2_B11                                          1_16
4 UML_NARWHAL_R2_B11                                          1_17
5 UML_NARWHAL_R2_B11                                          2_52
6 UML_NARWHAL_R2_B11                                          3_19

In [61]:
length(unique(nonimmune_PCR$colony))
nrow(nonimmune_PCR)

[1] 51

[1] 114

In [62]:
nonimmune_PCR

    Tubelabel_species           Health_Status   Date_Extracted Raw_ng_ul
1   042024_BEL_CBC_T1_1146_OANN Diseased_Tissue 9_9_2024       14.6
2   042024_BEL_CBC_T1_933_SSID  Diseased_Tissue 9_9_2024       25.4
3   042024_BEL_CBC_T1_938_SSID  Diseased_Tissue 9_9_2024       4.08
4   042024_BEL_CBC_T1_940_SSID  Diseased_Tissue 9_9_2024       63.2
5   042024_BEL_CBC_T2_1030_SSID Diseased_Tissue 9_9_2024       24.6
6   042024_BEL_CBC_T3_1011_SSID Diseased_Tissue 9_9_2024       7.42
7   042024_BEL_CBC_T3_1012_SSID Diseased_Tissue 9_9_2024       32.2
8   042024_BEL_CBC_T3_1057_SSID Diseased_Tissue 9_9_2024       27.2
9   042024_BEL_CBC_T3_962_SSID  Diseased_Tissue 9_9_2024       19.4
10  052022_BEL_CBC_T1_10_PSTR   Diseased_Margin 6_15_2023      11.1
11  052022_BEL_CBC_T1_11_PSTR   Diseased_Tissue 6_15_2023      3.2
12  052022_BEL_CBC_T1_12_MCAV   Diseased_Margin 6_10_2022      7.52
13  052022_BEL_CBC_T1_13_MCAV   Diseased_Tissue 2022           4.3
14  052022_BEL_CBC_T1_17_SSID   Diseased_Tissue 2022
15  052022_BEL_CBC_T1_39_MCAV   Diseased_Margin 7_17_2024      7.32
16  052022_BEL_CBC_T1_4_PSTR    Healthy         6_8_2023       28.2
17  052022_BEL_CBC_T1_40_MCAV   Diseased_Margin 2022           13.9
18  052022_BEL_CBC_T1_41_OANN   Healthy         6_21_2023      11.1
19  052022_BEL_CBC_T1_52_PAST   Diseased_Tissue 6_17_2022      8.1
20  052022_BEL_CBC_T1_60_MCAV   Diseased_Tissue 7_19_2024      4.47
21  052022_BEL_CBC_T1_61_PAST   Healthy         8_19_2024      8.35
22  052022_BEL_CBC_T1_70_MCAV   Diseased_Tissue 6_14_2022      48.8
23  052022_BEL_CBC_T2_45_PSTR   Diseased_Margin 10_10_2023     22.8
24  052022_BEL_CBC_T2_46_PSTR   Diseased_Tissue 10_10_2023     63.9
25  052022_BEL_CBC_T2_60_PAST   Diseased_Margin 8_9_2024       2.44
26  052022_BEL_CBC_T2_62_PAST   Diseased_Tissue 11_2_2024      0.522
27  052022_BEL_CBC_T2_72_OFAV   Healthy         10_3_2023      47.6
28  052022_BEL_CBC_T3_40_MCAV   Diseased_Margin 6_14_2022      23
29  052022_BEL_CBC_T3_48_MCAV   Diseased_Margin 6_14_2022      25.2
30  052022_BEL_CBC_T3_49_MCAV   Diseased_Tissue 6_14_2022      32
⋮   ⋮                           ⋮               ⋮              ⋮
85  122022_BEL_CBC_T1_134_PAST  Diseased_Margin 8_9_2024       1.21
86  122022_BEL_CBC_T1_136_OANN  Diseased_Tissue 6_28_2023      12.1
87  122022_BEL_CBC_T1_139_PAST  Diseased_Tissue 8_9_2024       1.25
88  122022_BEL_CBC_T1_144_MCAV  Diseased_Tissue 7_19_2024      3.03
89  122022_BEL_CBC_T1_155_PAST  Healthy         8_19_2024      3.08
90  122022_BEL_CBC_T2_101_OFAV  Diseased_Margin 6_28_2023      13.3
91  122022_BEL_CBC_T2_102_OFAV  Diseased_Tissue 6_28_2023      56.1
92  122022_BEL_CBC_T2_116_PSTR  Diseased_Margin 7_11_2024      7.87
93  122022_BEL_CBC_T2_117_PSTR  Diseased_Tissue 7_3_2024       22.5
94  122022_BEL_CBC_T2_118_OANN  Diseased_Margin 6_28_2023      16
95  122022_BEL_CBC_T2_119_OANN  Diseased_Tissue 6_28_2023      6.7
96  122022_BEL_CBC_T2_85_MCAV   Healthy         8_12_2024      0.162
97  122022_BEL_CBC_T2_89_PAST   Healthy         9_11_2024      42.6
98  122022_BEL_CBC_T3_115_PAST  Diseased_Tissue 8_9_2024       1.21
99  122022_BEL_CBC_T3_122_PAST  Healthy         9_11_2024      1.79
100 122022_BEL_CBC_T3_129_PAST  Diseased_Margin 8_9_2024       0.976
101 122022_BEL_CBC_T3_132_MCAV  Diseased_Tissue 7_19_2024      14.1
102 122022_BEL_CBC_T3_133_MCAV  Diseased_Margin 7_17_2024      3.5
103 122022_BEL_CBC_T3_145_MCAV  Diseased_Tissue 7_19_2024      5.74
104 122022_BEL_CBC_T3_158_PSTR  Healthy         7_12_2024      8.87
105 122022_BEL_CBC_T4_10_OFAV   Diseased_Tissue 6_28_2023      6.4
106 122022_BEL_CBC_T4_12_PSTR   Diseased_Margin 7_11_2024      3.49
107 122022_BEL_CBC_T4_13_PSTR   Diseased_Tissue 7_3_2024       6.21
108 122022_BEL_CBC_T4_14_MCAV   Diseased_Margin 7_17_2024      5.99
109 122022_BEL_CBC_T4_15_MCAV   Diseased_Tissue 7_19_2024      2.03
110 122022_BEL_CBC_T4_35_PSTR   Diseased_Margin 7_11_2024      13
111 122022_BEL_CBC_T4_36_PSTR   Diseased_Tissue 7_3_2024       34.8
112 122022_BEL_CBC_T4_5_MCAV    Diseased_Margin 7_17_2024      14.5
113 122022_BEL_CBC_T4_6_MCAV    Diseased_Tissue 7_19_2024      37.3
114 122022_BEL_CBC_T4_9_OFAV    Diseased_Margin 6_28_2023      9
    Extraction_physical_location            Date_Enriched Microbe_Location
1   UML_NARWHAL_R2_B11
2   UML_NARWHAL_R2_B11
3   UML_NARWHAL_R2_B11
4   UML_NARWHAL_R2_B11
5   UML_NARWHAL_R2_B11
6   UML_NARWHAL_R2_B11
7   UML_NARWHAL_R2_B11
8   UML_NARWHAL_R2_B11
9   UML_NARWHAL_R2_B11
10  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R2_B1
11  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R2_B1
12  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  10_30_2024    UML_NARWHAL_R6_B27
13  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  11_8_2024     UML_NARWHAL_R6_B27
14  UML_NARWHAL_R2_B32,  UML_NARWHAL_R2_B35
15  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
16  UML_NARWHAL_R2_B3                       10_6_2023     UML_NARWHAL_R6_B1
17  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  11_8_2024     UML_NARWHAL_R6_B27
18  UML_NARWHAL_R2_B3                       10_16_2023    UML_NARWHAL_R6_B1
19  UML_NARWHAL_R2_B32                      10_30_2024    UML_NARWHAL_R6_B27
20  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
21  UML_NARWHAL_R2_B29, UML_NARWHAL_R2_B34  9_28_2024     UML_NARWHAL_R6_B30
22  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  10_30_2024    UML_NARWHAL_R6_B27
23  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R2_B1
24  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R2_B1
25  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
26  UML_NARWHAL_R2_B29                      11_8_2024     UML_NARWHAL_R6_B27
27  UML_NARWHAL_R2_B3                       10_11_23      UML_NARWHAL_R6_B1
28  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  10_30_2024    UML_NARWHAL_R6_B27
29  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  10_30_2024    UML_NARWHAL_R6_B27
30  UML_NARWHAL_R2_B32, UML_NARWHAL_R2_B35  10_30_2024    UML_NARWHAL_R6_B27
⋮   ⋮                                       ⋮             ⋮
85  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
86  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
87  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
88  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
89  UML_NARWHAL_R2_B29, UML_NARWHAL_R2_B34  9_28_2024     UML_NARWHAL_R6_B30
90  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
91  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
92  UML_NARWHAL_R2_B26                      8_2_2024      UML_NARWHAL_R6_B27
93  UML_NARWHAL_R2_B26                      8_2_2024      UML_NARWHAL_R6_B27
94  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
95  UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
96  UML_NARWHAL_R2_B29                      11_6_2024     UML_NARWHAL_R6_B27
97  UML_NARWHAL_R2_B29                      10_6_2024     UML_NARWHAL_R6_B30
98  UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
99  UML_NARWHAL_R2_B29                      9_28_2024     UML_NARWHAL_R6_B30
100 UML_NARWHAL_R2_B29                      11_8_2024     UML_NARWHAL_R6_B27
101 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
102 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
103 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
104 UML_NARWHAL_R2_B26                      8_6_2024      UML_NARWHAL_R6_B27
105 UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
106 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
107 UML_NARWHAL_R2_B26                      8_2_2024      UML_NARWHAL_R6_B27
108 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
109 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
110 UML_NARWHAL_R2_B26                      8_2_2024      UML_NARWHAL_R6_B27
111 UML_NARWHAL_R2_B26                      8_2_2024      UML_NARWHAL_R6_B27
112 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
113 UML_NARWHAL_R2_B26                      10_29_2024    UML_NARWHAL_R6_B30
114 UML_NARWHAL_R2_B3                       10_17_2023    UML_NARWHAL_R6_B1
    colony
1   1_22
2   1_5
3   1_16
4   1_17
5   2_52
6   3_19
7   3_3
8   3_28
9   3_36
10  1_4
11  1_4
12  1_8
13  1_8
14  1_17
15  1_14
16  1_6
17  1_15
18  1_22
19  1_19
20  1_14
21  1_20
22  1_15
23  2_70
24  2_70
25  2_56
26  2_56
27  2_80
28  3_22
29  3_15
30  3_15
⋮   ⋮
85  1_20
86  1_22
87  1_20
88  1_8
89  1_19
90  2_80
91  2_80
92  2_28
93  2_28
94  2_30
95  2_30
96  2_59
97  2_56
98  3_18
99  3_24
100 3_18
101 3_15
102 3_15
103 3_67
104 3_74
105 4_100
106 4_96
107 4_96
108 4_95
109 4_95
110 4_97
111 4_97
112 4_94
113 4_94
114 4_100

In [ ]:
#make spreadsheet with all immune metagenomics 
write.csv(immune_metagenomics_PCR, file="~/Documents/SCTLD/Coral_Code/NSF_Rapid/CBC_PCR_Plan/2_immune_metagenomics_PCR.csv")